/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bravo;

import Intervencion.Intervencion;
import Sesion.Sesion;
import Sesion.Usuario;
import static bravo.VistaPrincipal.contenedor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author Edgar
 */
public class PanelPrincipal extends javax.swing.JPanel {
    
    Usuario usuario;
    Sesion sesion;
    GestorFinalizarIntervencion gestor;

    public PanelPrincipal(Usuario usuario, Sesion sesion, GestorFinalizarIntervencion gestor) {
        this.usuario = usuario;
        this.sesion = sesion;
        this.gestor = gestor;
        
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinalizar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 500));

        btnFinalizar.setText("Finalizar Intervencion");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lblTitulo.setText("Bienvenido a Sistema de Gestion Bravo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnFinalizar)))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addGap(112, 112, 112)
                .addComponent(btnFinalizar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //metodo 2
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        //metodo 3
        ArrayList<Intervencion> intervencionesEnCurso = gestor.opcionFinalizarIntervencion(sesion, usuario);
        System.out.println("tamaño "+intervencionesEnCurso.size());
        //metodo 18

        PanelIntervenciones panelIntervenciones = new PanelIntervenciones(intervencionesEnCurso, gestor);

        this.setVisible(false);
        contenedor.add(panelIntervenciones);
    }//GEN-LAST:event_btnFinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    /*@Override
    public void actionPerformed(ActionEvent arg0) {
        PanelIntervenciones panelIntervenciones = new PanelIntervenciones();
        Object evt = arg0.getSource();
        
        if(evt.equals(btnFinalizar)){
            this.setVisible(false);
            contenedor.add(panelIntervenciones);
        }
    }*/
}
