/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bravo;

import Interfaz.TablaIntervenciones;
import Intervencion.Intervencion;
import static bravo.VistaPrincipal.contenedor;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar
 */
public class PanelIntervenciones extends javax.swing.JPanel {

    GestorFinalizarIntervencion gestor;
    ArrayList<Intervencion> intervencionesEnCurso;

    public PanelIntervenciones(ArrayList<Intervencion> intervencionesEnCurso, GestorFinalizarIntervencion gestor) {
        this.intervencionesEnCurso = intervencionesEnCurso;
        this.gestor = gestor;
        
        initComponents();
        //metodo 18
        mostrarIntervencionesEnCurso(intervencionesEnCurso);

        //metodo 19
        JOptionPane.showMessageDialog(null, "Seleccione la intervencion que desea finalizar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jButton1.setText("Seleccionar Intervencion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarIntervencion(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jLabel1.setText("Intervenciones En Curso");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scroll.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarIntervencion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarIntervencion

        int filaSeleccionada = tabla.getSelectedRow();
        try {
            if (filaSeleccionada != -1) {
                
                Intervencion intervencionSeleccionada = intervencionesEnCurso.get(filaSeleccionada);
                
                //metodo 20
                String[][] matrizDotaciones = tomarSeleccionIntervencion(intervencionSeleccionada);
                
                //metodo 28
                PanelDotaciones panelDotaciones = new PanelDotaciones(matrizDotaciones);

                this.setVisible(false);
                contenedor.add(panelDotaciones);
                
            } else {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna intervencion");
            }
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex + "\nInténtelo nuevamente", " .::Error En la Operacion::.", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_seleccionarIntervencion

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //PanelPrincipal panelPrincipal = new PanelPrincipal();

        //this.setVisible(false);
        //contenedor.add(panelPrincipal);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    //metodo18
    public void mostrarIntervencionesEnCurso(ArrayList<Intervencion> intervencionesEnCurso) {

        System.out.println("panel " + intervencionesEnCurso.size());
        TablaIntervenciones t1 = new TablaIntervenciones();
        DefaultTableModel modelo = t1.armarTableModel(intervencionesEnCurso);
        System.out.println(modelo.toString());
        tabla.setModel(modelo);
    }

    //metodo 20
    public String[][] tomarSeleccionIntervencion(Intervencion intervencionSeleccionada) {
        String[][] matriz = gestor.tomarSeleccionIntervencion(intervencionSeleccionada);
        return matriz;
    }
}
